### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by MathiasGaeng** [StonySr/KafiMSP#1]
Grafische Gestaltung des Interfaces mit den wichtigsten Funktionen / Buttons

**Comment by MathiasGaeng** [comment]
> Grafische Gestaltung des Interfaces mit den wichtigsten Funktionen / Buttons

**Comment by MathiasGaeng** [comment]
- [ ] Brainstorming
- [ ] Bewertung der Ideen
- [ ] @StonySr - Präsentation im Core Team

**Comment by Skruzsil** [comment]
Erste Entwicklung abgeschlossen, bereit für Test
