### ISSUE TITLE
Kreditkartenbezahlung failed

### ISSUE THREAD

**Issue by Skruzsil** [StonySr/KafiMSP#7]
Bei Kreditkartenzahlung kann nicht vollständig Kreditkarten-Nummer erfasst werden -> **Nummernfeld zu klein**

**Comment by MathiasGaeng** [comment]
@Skruzsil 
Bitte detaillierte Fehlerbeschreibung zusenden

**Comment by Skruzsil** [comment]
Issue solved, Feld vergrössert, Test ok
