### ISSUE TITLE
Miete für Testlokal organisieren

### ISSUE THREAD

**Issue by StonySr** [StonySr/KafiMSP#9]
Bahnhofstrasse 36 Vertrag abschliessen

**Comment by Skruzsil** [comment]
Lokal ermittelt, Vertragsverhandlungen gestartet (Lanzeitmiete)

**Comment by Skruzsil** [comment]
Vertrag Unterschrieben - Lokal für 5 Jahre gemietet, automatische Verlängerung jeweils um 1 Jahr
